/*
 * FAN - Framework for Applications in Networks
 * Copyright (C) 2004 FreshX [dominik@freshx.de]
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */



#ifndef PAE_BUILDNR
#define PAE_BUILDNR

#include <string>
using namespace std;
extern int asprintf(char **p, const char* p2, ...);

/**
 * Autogenerated BuildNumber Class
 */
class FAN_BuildNumber
{
	static int version;
	static int release;
	static int buildnr;	
public:
	static char *buildos;
	static char *buildPlatform;
	static char *buildOSName;
	static char *buildNode;

	/**
	 * @return Current build number
	 */
	static char *aGetBuild(void){
		char *buf;
		asprintf(&buf,"%.2d-%.2d-%s-%.5d",version,release,buildPlatform,buildnr);
		return buf;
	}
};

#endif
